import type { Season } from '@/lib/types';

export interface SeasonPaletteSwatch {
  hex: string;
  name: string;
}

export interface SeasonPaletteData {
  name: string;
  palette: SeasonPaletteSwatch[];
}

export const SEASON_PALETTES: Record<Season, SeasonPaletteData> = {
  bright_winter: {
    name: 'Bright Winter',
    palette: [
      { hex: '#E8E4E1', name: 'Porcelain' },
      { hex: '#C8C3D0', name: 'Lavender Mist' },
      { hex: '#9B8FA8', name: 'Lilac Smoke' },
      { hex: '#6B5B7F', name: 'Royal Plum' },
      { hex: '#3D405B', name: 'Midnight Navy' },
      { hex: '#2C4251', name: 'Deep Sapphire' },
      { hex: '#1B5664', name: 'Arctic Teal' },
      { hex: '#0F6E7A', name: 'Turquoise Jewel' },
      { hex: '#0A7C88', name: 'Emerald Sea' },
      { hex: '#39A896', name: 'Mint Ice' },
      { hex: '#6EC4B8', name: 'Aquamarine' },
      { hex: '#A5DFD3', name: 'Frozen Mint' },
      { hex: '#D4B5D6', name: 'Orchid Petal' },
      { hex: '#E8A5C3', name: 'Pink Diamond' },
      { hex: '#F282A7', name: 'Hot Pink' },
      { hex: '#D95F88', name: 'Magenta Kiss' },
    ],
  },
  cool_winter: {
    name: 'Cool Winter',
    palette: [
      { hex: '#F5F5F5', name: 'Alabaster' },
      { hex: '#E0E0E0', name: 'Pearl' },
      { hex: '#9FA8DA', name: 'Periwinkle' },
      { hex: '#7986CB', name: 'Cornflower' },
      { hex: '#5C6BC0', name: 'True Blue' },
      { hex: '#3F51B5', name: 'Royal Blue' },
      { hex: '#3949AB', name: 'Cobalt' },
      { hex: '#303F9F', name: 'Indigo Night' },
      { hex: '#1A237E', name: 'Navy Eclipse' },
      { hex: '#4A148C', name: 'Deep Violet' },
      { hex: '#6A1B9A', name: 'Imperial Purple' },
      { hex: '#8E24AA', name: 'Amethyst' },
      { hex: '#9C27B0', name: 'Purple Reign' },
      { hex: '#AB47BC', name: 'Orchid' },
      { hex: '#CE93D8', name: 'Lilac Dream' },
      { hex: '#F3E5F5', name: 'Lavender Blush' },
    ],
  },
  deep_winter: {
    name: 'Deep Winter',
    palette: [
      { hex: '#4A4A4A', name: 'Charcoal' },
      { hex: '#3D3D3D', name: 'Graphite' },
      { hex: '#5D4E6D', name: 'Eggplant' },
      { hex: '#4A3B5C', name: 'Deep Plum' },
      { hex: '#2C3E50', name: 'Midnight Blue' },
      { hex: '#34495E', name: 'Stormy Night' },
      { hex: '#16697A', name: 'Deep Teal' },
      { hex: '#1A7F8E', name: 'Ocean Depth' },
      { hex: '#0D7377', name: 'Pine Green' },
      { hex: '#14A085', name: 'Emerald' },
      { hex: '#27AE60', name: 'Forest Jewel' },
      { hex: '#2ECC71', name: 'Jade' },
      { hex: '#8E44AD', name: 'Byzantine Purple' },
      { hex: '#9B59B6', name: 'Violet Storm' },
      { hex: '#C0392B', name: 'Ruby Red' },
      { hex: '#E74C3C', name: 'Crimson' },
    ],
  },
  bright_spring: {
    name: 'Bright Spring',
    palette: [
      { hex: '#FFF9E6', name: 'Vanilla Cream' },
      { hex: '#FFE5B4', name: 'Buttercream' },
      { hex: '#FFD966', name: 'Golden Honey' },
      { hex: '#FFC845', name: 'Sunshine' },
      { hex: '#FFB347', name: 'Tangerine' },
      { hex: '#FF9A3C', name: 'Mango Sorbet' },
      { hex: '#FF6B6B', name: 'Coral Reef' },
      { hex: '#FF5252', name: 'Poppy Red' },
      { hex: '#E91E63', name: 'Hot Fuchsia' },
      { hex: '#FF4081', name: 'Bright Pink' },
      { hex: '#F06292', name: 'Bubblegum' },
      { hex: '#EC407A', name: 'Pink Punch' },
      { hex: '#AB47BC', name: 'Bright Orchid' },
      { hex: '#BA68C8', name: 'Violet Pop' },
      { hex: '#9575CD', name: 'Electric Lilac' },
      { hex: '#7E57C2', name: 'Vivid Purple' },
    ],
  },
  warm_spring: {
    name: 'Warm Spring',
    palette: [
      { hex: '#FFF8DC', name: 'Cream' },
      { hex: '#FFEAA7', name: 'Lemon Chiffon' },
      { hex: '#FDCB6E', name: 'Golden Glow' },
      { hex: '#F39C12', name: 'Marigold' },
      { hex: '#E67E22', name: 'Pumpkin Spice' },
      { hex: '#D35400', name: 'Burnt Orange' },
      { hex: '#E74C3C', name: 'Tomato Red' },
      { hex: '#C0392B', name: 'Brick Red' },
      { hex: '#8B4513', name: 'Saddle Brown' },
      { hex: '#A0522D', name: 'Sienna' },
      { hex: '#CD853F', name: 'Peru' },
      { hex: '#DEB887', name: 'Burlywood' },
      { hex: '#D2691E', name: 'Copper Penny' },
      { hex: '#B8860B', name: 'Dark Goldenrod' },
      { hex: '#DAA520', name: 'Goldenrod' },
      { hex: '#FFD700', name: 'True Gold' },
    ],
  },
  light_spring: {
    name: 'Light Spring',
    palette: [
      { hex: '#FFFACD', name: 'Lemon Chiffon' },
      { hex: '#FFE4B5', name: 'Peach Cream' },
      { hex: '#FFDAB9', name: 'Peach Puff' },
      { hex: '#FFCBA4', name: 'Apricot Blush' },
      { hex: '#FFB6A3', name: 'Soft Peach' },
      { hex: '#FFA59E', name: 'Pink Coral' },
      { hex: '#FF9AA2', name: 'Rose Quartz' },
      { hex: '#E8927C', name: 'Terracotta Blush' },
      { hex: '#D4A5A5', name: 'Dusty Rose' },
      { hex: '#C7A19F', name: 'Mauve Taupe' },
      { hex: '#B09E99', name: 'Warm Taupe' },
      { hex: '#9B8C8C', name: 'Pebble' },
      { hex: '#B4A7D6', name: 'Soft Lilac' },
      { hex: '#CAB8DC', name: 'Wisteria' },
      { hex: '#E0C9E0', name: 'Pale Orchid' },
      { hex: '#F5DAE3', name: 'Ballet Pink' },
    ],
  },
  light_summer: {
    name: 'Light Summer',
    palette: [
      { hex: '#F8F8FF', name: 'Ghost White' },
      { hex: '#E6E6FA', name: 'Lavender Mist' },
      { hex: '#D8BFD8', name: 'Thistle' },
      { hex: '#DDA0DD', name: 'Plum Blossom' },
      { hex: '#EE82EE', name: 'Violet' },
      { hex: '#DA70D6', name: 'Orchid Haze' },
      { hex: '#C899C8', name: 'Lilac Rose' },
      { hex: '#B595B5', name: 'Soft Mauve' },
      { hex: '#9D8FA8', name: 'Dusty Lilac' },
      { hex: '#8B7FA5', name: 'Heather' },
      { hex: '#7B6FA2', name: 'Lavender Gray' },
      { hex: '#6B5F9F', name: 'Purple Haze' },
      { hex: '#87CEEB', name: 'Sky Blue' },
      { hex: '#5DADE2', name: 'Powder Blue' },
      { hex: '#3498DB', name: 'Cornflower Blue' },
      { hex: '#2E86C1', name: 'Denim Blue' },
    ],
  },
  cool_summer: {
    name: 'Cool Summer',
    palette: [
      { hex: '#E8E4E1', name: 'Porcelain Rose' },
      { hex: '#D5D1D8', name: 'Silver Lilac' },
      { hex: '#B8AEB8', name: 'Dove Gray' },
      { hex: '#9B8FA8', name: 'Cool Mauve' },
      { hex: '#7E7491', name: 'Dusty Purple' },
      { hex: '#6B5B7F', name: 'Muted Plum' },
      { hex: '#574763', name: 'Soft Eggplant' },
      { hex: '#4A3B5C', name: 'Twilight Purple' },
      { hex: '#708090', name: 'Slate Gray' },
      { hex: '#778899', name: 'Light Slate' },
      { hex: '#87A0AF', name: 'Cool Blue Gray' },
      { hex: '#9BB4C5', name: 'Misty Blue' },
      { hex: '#9FA8B0', name: 'Silver Cloud' },
      { hex: '#B0A8A0', name: 'Cool Beige' },
      { hex: '#C0B0A0', name: 'Soft Taupe' },
      { hex: '#D0C0B0', name: 'Cocoa Rose' },
    ],
  },
  soft_summer: {
    name: 'Soft Summer',
    palette: [
      { hex: '#E8E4E1', name: 'Soft Ivory' },
      { hex: '#D3CBCD', name: 'Pale Mauve' },
      { hex: '#BEB2B8', name: 'Muted Rose' },
      { hex: '#A99AA3', name: 'Dusty Plum' },
      { hex: '#94828E', name: 'Soft Grape' },
      { hex: '#7E6B78', name: 'Smoky Mauve' },
      { hex: '#695563', name: 'Muted Eggplant' },
      { hex: '#54404D', name: 'Soft Aubergine' },
      { hex: '#8A9BA8', name: 'Soft Denim' },
      { hex: '#9AACB8', name: 'Misty Gray' },
      { hex: '#AABDC8', name: 'Soft Sky' },
      { hex: '#BACED8', name: 'Powder Blue' },
      { hex: '#9BA894', name: 'Sage Green' },
      { hex: '#A8B9A4', name: 'Soft Moss' },
      { hex: '#B5CAB4', name: 'Mint Cream' },
      { hex: '#C2DBC4', name: 'Seafoam' },
    ],
  },
  soft_autumn: {
    name: 'Soft Autumn',
    palette: [
      { hex: '#E8DCC8', name: 'Cream Beige' },
      { hex: '#D4C4A8', name: 'Wheat' },
      { hex: '#C0AC88', name: 'Soft Sand' },
      { hex: '#AC9468', name: 'Toffee' },
      { hex: '#8C7C54', name: 'Olive Taupe' },
      { hex: '#6C6440', name: 'Moss' },
      { hex: '#5A5238', name: 'Olive Brown' },
      { hex: '#4A4330', name: 'Cocoa' },
      { hex: '#8B7355', name: 'Soft Bronze' },
      { hex: '#A08968', name: 'Warm Taupe' },
      { hex: '#B59F7B', name: 'Camel' },
      { hex: '#CAB58E', name: 'Biscotti' },
      { hex: '#7B8A7A', name: 'Sage' },
      { hex: '#8FA08E', name: 'Soft Olive' },
      { hex: '#A3B6A2', name: 'Eucalyptus' },
      { hex: '#B7CCB6', name: 'Mint Green' },
    ],
  },
  warm_autumn: {
    name: 'Warm Autumn',
    palette: [
      { hex: '#F5E6D3', name: 'Warm Ivory' },
      { hex: '#E6C9A8', name: 'Almond' },
      { hex: '#D7AC7D', name: 'Golden Beige' },
      { hex: '#C88F52', name: 'Caramel' },
      { hex: '#B97A47', name: 'Toffee' },
      { hex: '#A0653C', name: 'Copper Brown' },
      { hex: '#875031', name: 'Rust' },
      { hex: '#6E3B26', name: 'Mahogany' },
      { hex: '#8B4513', name: 'Saddle Brown' },
      { hex: '#A0522D', name: 'Sienna' },
      { hex: '#B5651D', name: 'Burnt Sienna' },
      { hex: '#CA7810', name: 'Bronze' },
      { hex: '#C17A5B', name: 'Terra Cotta' },
      { hex: '#D68F6E', name: 'Coral Clay' },
      { hex: '#EBA481', name: 'Peach Bisque' },
      { hex: '#FFB994', name: 'Apricot' },
    ],
  },
  deep_autumn: {
    name: 'Deep Autumn',
    palette: [
      { hex: '#8B6F47', name: 'Bronze' },
      { hex: '#7D5E3C', name: 'Chestnut' },
      { hex: '#6F4E31', name: 'Walnut' },
      { hex: '#613D26', name: 'Coffee Bean' },
      { hex: '#532D1B', name: 'Espresso' },
      { hex: '#451C10', name: 'Dark Chocolate' },
      { hex: '#6B3410', name: 'Burnt Umber' },
      { hex: '#7D4520', name: 'Cinnamon' },
      { hex: '#8F5630', name: 'Spice' },
      { hex: '#A16740', name: 'Caramel' },
      { hex: '#654321', name: 'Dark Brown' },
      { hex: '#8B4513', name: 'Saddle Brown' },
      { hex: '#A0522D', name: 'Sienna' },
      { hex: '#CD853F', name: 'Peru' },
      { hex: '#DEB887', name: 'Burlywood' },
      { hex: '#F4A460', name: 'Sandy Brown' },
    ],
  },
};
